"""order line progress tracking

Revision ID: 0458859fae6a
Revises: 0742db758c6f
Create Date: 2026-09-26 15:46:14.147429
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0458859fae6a'
down_revision: str | None = '0742db758c6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_lines', sa.Column('qty_received', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False), schema='purchasing')
    op.add_column('purchase_order_lines', sa.Column('qty_invoiced', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False), schema='purchasing')
    op.add_column('sales_order_lines', sa.Column('qty_delivered', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False), schema='sales')
    op.add_column('sales_order_lines', sa.Column('qty_invoiced', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False), schema='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order_lines', 'qty_invoiced', schema='sales')
    op.drop_column('sales_order_lines', 'qty_delivered', schema='sales')
    op.drop_column('purchase_order_lines', 'qty_invoiced', schema='purchasing')
    op.drop_column('purchase_order_lines', 'qty_received', schema='purchasing')
    # ### end Alembic commands ###
