"""accounting tables

Revision ID: 0742db758c6f
Revises: 524b04840d15
Create Date: 2026-09-25 23:28:55.683050
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0742db758c6f'
down_revision: str | None = '524b04840d15'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounting.accounts.id'], name=op.f('fk_accounts_parent_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_accounts_org_id')),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_accounts_org_id'), 'accounts', ['org_id'], unique=False, schema='accounting')
    op.create_table('journal_entries',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_journal_entries_org_id')),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_journal_entries_org_id'), 'journal_entries', ['org_id'], unique=False, schema='accounting')
    op.create_index(op.f('ix_accounting_journal_entries_source_id'), 'journal_entries', ['source_id'], unique=False, schema='accounting')
    op.create_index(op.f('ix_accounting_journal_entries_source_type'), 'journal_entries', ['source_type'], unique=False, schema='accounting')
    op.create_table('journal_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.accounts.id'], name=op.f('fk_journal_lines_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['accounting.journal_entries.id'], name=op.f('fk_journal_lines_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines')),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False, schema='accounting')
    op.create_index(op.f('ix_accounting_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False, schema='accounting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_journal_lines_entry_id'), table_name='journal_lines', schema='accounting')
    op.drop_index(op.f('ix_accounting_journal_lines_account_id'), table_name='journal_lines', schema='accounting')
    op.drop_table('journal_lines', schema='accounting')
    op.drop_index(op.f('ix_accounting_journal_entries_source_type'), table_name='journal_entries', schema='accounting')
    op.drop_index(op.f('ix_accounting_journal_entries_source_id'), table_name='journal_entries', schema='accounting')
    op.drop_index(op.f('ix_accounting_journal_entries_org_id'), table_name='journal_entries', schema='accounting')
    op.drop_table('journal_entries', schema='accounting')
    op.drop_index(op.f('ix_accounting_accounts_org_id'), table_name='accounts', schema='accounting')
    op.drop_table('accounts', schema='accounting')
    # ### end Alembic commands ###
