"""payment credit note link

Revision ID: 30e029e0856b
Revises: cfdb5277a3cb
Create Date: 2026-09-26 19:01:06.602074
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '30e029e0856b'
down_revision: str | None = 'cfdb5277a3cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('credit_note_id', sa.Uuid(), nullable=True), schema='invoicing')
    op.create_index(op.f('ix_invoicing_payments_credit_note_id'), 'payments', ['credit_note_id'], unique=False, schema='invoicing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoicing_payments_credit_note_id'), table_name='payments', schema='invoicing')
    op.drop_column('payments', 'credit_note_id', schema='invoicing')
    # ### end Alembic commands ###
