"""payment currency fields

Revision ID: 3dd3b49c3f42
Revises: 7901befb3acb
Create Date: 2026-09-26 20:19:58.070075
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3dd3b49c3f42'
down_revision: str | None = '7901befb3acb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_currencies_org_id')),
    schema='core'
    )
    op.create_index(op.f('ix_core_currencies_org_id'), 'currencies', ['org_id'], unique=False, schema='core')
    op.create_table('fx_rates',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates')),
    sa.UniqueConstraint('org_id', 'currency', 'rate_date', name=op.f('uq_fx_rates_org_id')),
    schema='core'
    )
    op.create_index(op.f('ix_core_fx_rates_currency'), 'fx_rates', ['currency'], unique=False, schema='core')
    op.create_index(op.f('ix_core_fx_rates_org_id'), 'fx_rates', ['org_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False, schema='core')
    op.add_column('payments', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False), schema='invoicing')
    op.add_column('payments', sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), server_default='1', nullable=False), schema='invoicing')
    op.add_column('payments', sa.Column('amount_base', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False), schema='invoicing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount_base', schema='invoicing')
    op.drop_column('payments', 'fx_rate', schema='invoicing')
    op.drop_column('payments', 'currency', schema='invoicing')
    op.drop_index(op.f('ix_core_fx_rates_rate_date'), table_name='fx_rates', schema='core')
    op.drop_index(op.f('ix_core_fx_rates_org_id'), table_name='fx_rates', schema='core')
    op.drop_index(op.f('ix_core_fx_rates_currency'), table_name='fx_rates', schema='core')
    op.drop_table('fx_rates', schema='core')
    op.drop_index(op.f('ix_core_currencies_org_id'), table_name='currencies', schema='core')
    op.drop_table('currencies', schema='core')
    # ### end Alembic commands ###
