"""accounting tables

Revision ID: 524b04840d15
Revises: 7de2de8d96de
Create Date: 2026-09-25 23:27:08.209892
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '524b04840d15'
down_revision: str | None = '7de2de8d96de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
