"""fx rates and document base totals

Revision ID: 7901befb3acb
Revises: 30e029e0856b
Create Date: 2026-09-26 20:02:42.956660
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7901befb3acb'
down_revision: str | None = '30e029e0856b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), server_default='1', nullable=False), schema='invoicing')
    op.add_column('invoices', sa.Column('total_base', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False), schema='invoicing')
    op.add_column('purchase_orders', sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), server_default='1', nullable=False), schema='purchasing')
    op.add_column('purchase_orders', sa.Column('total_base', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False), schema='purchasing')
    op.add_column('quotations', sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), server_default='1', nullable=False), schema='sales')
    op.add_column('quotations', sa.Column('total_base', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False), schema='sales')
    op.add_column('sales_orders', sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), server_default='1', nullable=False), schema='sales')
    op.add_column('sales_orders', sa.Column('total_base', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False), schema='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'total_base', schema='sales')
    op.drop_column('sales_orders', 'fx_rate', schema='sales')
    op.drop_column('quotations', 'total_base', schema='sales')
    op.drop_column('quotations', 'fx_rate', schema='sales')
    op.drop_column('purchase_orders', 'total_base', schema='purchasing')
    op.drop_column('purchase_orders', 'fx_rate', schema='purchasing')
    op.drop_column('invoices', 'total_base', schema='invoicing')
    op.drop_column('invoices', 'fx_rate', schema='invoicing')
    # ### end Alembic commands ###
