"""invoicing tables

Revision ID: 7de2de8d96de
Revises: 86369f846e76
Create Date: 2026-09-25 23:12:37.705859
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7de2de8d96de'
down_revision: str | None = '86369f846e76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_type', sa.String(length=2), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_number', sa.String(length=30), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['crm.contacts.id'], name=op.f('fk_invoices_party_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_invoices_org_id')),
    schema='invoicing'
    )
    op.create_index(op.f('ix_invoicing_invoices_invoice_type'), 'invoices', ['invoice_type'], unique=False, schema='invoicing')
    op.create_index(op.f('ix_invoicing_invoices_org_id'), 'invoices', ['org_id'], unique=False, schema='invoicing')
    op.create_index(op.f('ix_invoicing_invoices_status'), 'invoices', ['status'], unique=False, schema='invoicing')
    op.create_table('payments',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['crm.contacts.id'], name=op.f('fk_payments_party_id_contacts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_payments_org_id')),
    schema='invoicing'
    )
    op.create_index(op.f('ix_invoicing_payments_org_id'), 'payments', ['org_id'], unique=False, schema='invoicing')
    op.create_index(op.f('ix_invoicing_payments_status'), 'payments', ['status'], unique=False, schema='invoicing')
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=True),
    sa.Column('tax_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoicing.invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_invoice_lines_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_id'], ['catalog.taxes.id'], name=op.f('fk_invoice_lines_tax_id_taxes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines')),
    schema='invoicing'
    )
    op.create_index(op.f('ix_invoicing_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False, schema='invoicing')
    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoicing.invoices.id'], name=op.f('fk_payment_allocations_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['invoicing.payments.id'], name=op.f('fk_payment_allocations_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations')),
    schema='invoicing'
    )
    op.create_index(op.f('ix_invoicing_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False, schema='invoicing')
    op.create_index(op.f('ix_invoicing_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False, schema='invoicing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoicing_payment_allocations_payment_id'), table_name='payment_allocations', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_payment_allocations_invoice_id'), table_name='payment_allocations', schema='invoicing')
    op.drop_table('payment_allocations', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_invoice_lines_invoice_id'), table_name='invoice_lines', schema='invoicing')
    op.drop_table('invoice_lines', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_payments_status'), table_name='payments', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_payments_org_id'), table_name='payments', schema='invoicing')
    op.drop_table('payments', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_invoices_status'), table_name='invoices', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_invoices_org_id'), table_name='invoices', schema='invoicing')
    op.drop_index(op.f('ix_invoicing_invoices_invoice_type'), table_name='invoices', schema='invoicing')
    op.drop_table('invoices', schema='invoicing')
    # ### end Alembic commands ###
