"""inventory tables

Revision ID: 86369f846e76
Revises: fd4d2439f3d1
Create Date: 2026-09-25 22:59:11.861801
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '86369f846e76'
down_revision: str | None = 'fd4d2439f3d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('last_move_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock')),
    sa.UniqueConstraint('org_id', 'product_id', 'warehouse_id', name=op.f('uq_stock_org_id')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_org_id'), 'stock', ['org_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_product_id'), 'stock', ['product_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_warehouse_id'), 'stock', ['warehouse_id'], unique=False, schema='inventory')
    op.create_table('stock_moves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('move_type', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('ref_number', sa.String(length=30), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('reverses_move_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_moves')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_moves_move_type'), 'stock_moves', ['move_type'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_moves_org_id'), 'stock_moves', ['org_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_moves_product_id'), 'stock_moves', ['product_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_moves_reverses_move_id'), 'stock_moves', ['reverses_move_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_moves_warehouse_id'), 'stock_moves', ['warehouse_id'], unique=False, schema='inventory')
    op.create_table('warehouses',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_warehouses_branch_id_branches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_warehouses_org_id')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_warehouses_org_id'), 'warehouses', ['org_id'], unique=False, schema='inventory')
    op.create_table('adjustments',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory.warehouses.id'], name=op.f('fk_adjustments_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustments')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_adjustments_org_id')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_adjustments_org_id'), 'adjustments', ['org_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_adjustments_status'), 'adjustments', ['status'], unique=False, schema='inventory')
    op.create_table('deliveries',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory.warehouses.id'], name=op.f('fk_deliveries_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_deliveries_org_id')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_deliveries_org_id'), 'deliveries', ['org_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_deliveries_status'), 'deliveries', ['status'], unique=False, schema='inventory')
    op.create_table('receipts',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory.warehouses.id'], name=op.f('fk_receipts_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_receipts_org_id')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_receipts_org_id'), 'receipts', ['org_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_receipts_status'), 'receipts', ['status'], unique=False, schema='inventory')
    op.create_table('adjustment_lines',
    sa.Column('adjustment_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['inventory.adjustments.id'], name=op.f('fk_adjustment_lines_adjustment_id_adjustments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustment_lines')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_adjustment_lines_adjustment_id'), 'adjustment_lines', ['adjustment_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_adjustment_lines_product_id'), 'adjustment_lines', ['product_id'], unique=False, schema='inventory')
    op.create_table('delivery_lines',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['inventory.deliveries.id'], name=op.f('fk_delivery_lines_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_lines')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_delivery_lines_delivery_id'), 'delivery_lines', ['delivery_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_delivery_lines_product_id'), 'delivery_lines', ['product_id'], unique=False, schema='inventory')
    op.create_table('receipt_lines',
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['inventory.receipts.id'], name=op.f('fk_receipt_lines_receipt_id_receipts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_lines')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_receipt_lines_product_id'), 'receipt_lines', ['product_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_receipt_lines_receipt_id'), 'receipt_lines', ['receipt_id'], unique=False, schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_receipt_lines_receipt_id'), table_name='receipt_lines', schema='inventory')
    op.drop_index(op.f('ix_inventory_receipt_lines_product_id'), table_name='receipt_lines', schema='inventory')
    op.drop_table('receipt_lines', schema='inventory')
    op.drop_index(op.f('ix_inventory_delivery_lines_product_id'), table_name='delivery_lines', schema='inventory')
    op.drop_index(op.f('ix_inventory_delivery_lines_delivery_id'), table_name='delivery_lines', schema='inventory')
    op.drop_table('delivery_lines', schema='inventory')
    op.drop_index(op.f('ix_inventory_adjustment_lines_product_id'), table_name='adjustment_lines', schema='inventory')
    op.drop_index(op.f('ix_inventory_adjustment_lines_adjustment_id'), table_name='adjustment_lines', schema='inventory')
    op.drop_table('adjustment_lines', schema='inventory')
    op.drop_index(op.f('ix_inventory_receipts_status'), table_name='receipts', schema='inventory')
    op.drop_index(op.f('ix_inventory_receipts_org_id'), table_name='receipts', schema='inventory')
    op.drop_table('receipts', schema='inventory')
    op.drop_index(op.f('ix_inventory_deliveries_status'), table_name='deliveries', schema='inventory')
    op.drop_index(op.f('ix_inventory_deliveries_org_id'), table_name='deliveries', schema='inventory')
    op.drop_table('deliveries', schema='inventory')
    op.drop_index(op.f('ix_inventory_adjustments_status'), table_name='adjustments', schema='inventory')
    op.drop_index(op.f('ix_inventory_adjustments_org_id'), table_name='adjustments', schema='inventory')
    op.drop_table('adjustments', schema='inventory')
    op.drop_index(op.f('ix_inventory_warehouses_org_id'), table_name='warehouses', schema='inventory')
    op.drop_table('warehouses', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_moves_warehouse_id'), table_name='stock_moves', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_moves_reverses_move_id'), table_name='stock_moves', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_moves_product_id'), table_name='stock_moves', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_moves_org_id'), table_name='stock_moves', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_moves_move_type'), table_name='stock_moves', schema='inventory')
    op.drop_table('stock_moves', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_warehouse_id'), table_name='stock', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_product_id'), table_name='stock', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_org_id'), table_name='stock', schema='inventory')
    op.drop_table('stock', schema='inventory')
    # ### end Alembic commands ###
