"""crm and catalog tables

Revision ID: aa3464ba149d
Revises: b9e6fb7f8da0
Create Date: 2026-09-25 22:22:47.435810
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'aa3464ba149d'
down_revision: str | None = 'b9e6fb7f8da0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.product_categories.id'], name=op.f('fk_product_categories_parent_id_product_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_product_categories_org_id'), 'product_categories', ['org_id'], unique=False, schema='catalog')
    op.create_table('taxes',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applies_to', sa.String(length=10), nullable=False),
    sa.Column('is_default_sale', sa.Boolean(), nullable=False),
    sa.Column('is_default_purchase', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxes')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_taxes_org_id')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_taxes_org_id'), 'taxes', ['org_id'], unique=False, schema='catalog')
    op.create_table('uoms',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uoms')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_uoms_org_id')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_uoms_org_id'), 'uoms', ['org_id'], unique=False, schema='catalog')
    op.create_table('products',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('is_purchasable', sa.Boolean(), nullable=False),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sale_tax_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_tax_id', sa.Uuid(), nullable=True),
    sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('image_key', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_tax_id'], ['catalog.taxes.id'], name=op.f('fk_products_purchase_tax_id_taxes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_tax_id'], ['catalog.taxes.id'], name=op.f('fk_products_sale_tax_id_taxes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uom_id'], ['catalog.uoms.id'], name=op.f('fk_products_uom_id_uoms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('org_id', 'sku', name=op.f('uq_products_org_id')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_products_org_id'), 'products', ['org_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_products_sku'), 'products', ['sku'], unique=False, schema='catalog')
    op.create_table('contacts',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['core.users.id'], name=op.f('fk_contacts_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('org_id', 'code', name=op.f('uq_contacts_org_id')),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_contacts_code'), 'contacts', ['code'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_contacts_org_id'), 'contacts', ['org_id'], unique=False, schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_contacts_org_id'), table_name='contacts', schema='crm')
    op.drop_index(op.f('ix_crm_contacts_code'), table_name='contacts', schema='crm')
    op.drop_table('contacts', schema='crm')
    op.drop_index(op.f('ix_catalog_products_sku'), table_name='products', schema='catalog')
    op.drop_index(op.f('ix_catalog_products_org_id'), table_name='products', schema='catalog')
    op.drop_table('products', schema='catalog')
    op.drop_index(op.f('ix_catalog_uoms_org_id'), table_name='uoms', schema='catalog')
    op.drop_table('uoms', schema='catalog')
    op.drop_index(op.f('ix_catalog_taxes_org_id'), table_name='taxes', schema='catalog')
    op.drop_table('taxes', schema='catalog')
    op.drop_index(op.f('ix_catalog_product_categories_org_id'), table_name='product_categories', schema='catalog')
    op.drop_table('product_categories', schema='catalog')
    # ### end Alembic commands ###
