"""ai drafts

Revision ID: b667c1134da5
Revises: e588436554b0
Create Date: 2026-09-26 20:52:24.195432
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b667c1134da5'
down_revision: str | None = 'e588436554b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_drafts',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_drafts')),
    schema='core'
    )
    op.create_index(op.f('ix_core_ai_drafts_entity_id'), 'ai_drafts', ['entity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ai_drafts_entity_type'), 'ai_drafts', ['entity_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ai_drafts_org_id'), 'ai_drafts', ['org_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ai_drafts_status'), 'ai_drafts', ['status'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_ai_drafts_status'), table_name='ai_drafts', schema='core')
    op.drop_index(op.f('ix_core_ai_drafts_org_id'), table_name='ai_drafts', schema='core')
    op.drop_index(op.f('ix_core_ai_drafts_entity_type'), table_name='ai_drafts', schema='core')
    op.drop_index(op.f('ix_core_ai_drafts_entity_id'), table_name='ai_drafts', schema='core')
    op.drop_table('ai_drafts', schema='core')
    # ### end Alembic commands ###
