"""core tables

Revision ID: b9e6fb7f8da0
Revises: 0001
Create Date: 2026-09-25 22:01:55.233846
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b9e6fb7f8da0'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='core'
    )
    op.create_index(op.f('ix_core_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='core')
    op.create_table('document_sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('org_id', 'entity', 'year', name=op.f('uq_document_sequences_org_id')),
    schema='core'
    )
    op.create_index(op.f('ix_core_document_sequences_org_id'), 'document_sequences', ['org_id'], unique=False, schema='core')
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    schema='core'
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_permissions_code'), 'permissions', ['code'], unique=True, schema='core')
    op.create_index(op.f('ix_core_permissions_module'), 'permissions', ['module'], unique=False, schema='core')
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code')),
    schema='core'
    )
    op.create_table('branches',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['core.organizations.id'], name=op.f('fk_branches_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    schema='core'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions')),
    schema='core'
    )
    op.create_table('settings',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['core.organizations.id'], name=op.f('fk_settings_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('org_id', 'key', name=op.f('uq_settings_org_id')),
    schema='core'
    )
    op.create_index(op.f('ix_core_settings_org_id'), 'settings', ['org_id'], unique=False, schema='core')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('default_branch_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_branch_id'], ['core.branches.id'], name=op.f('fk_users_default_branch_id_branches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='core'
    )
    op.create_index(op.f('ix_core_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='core')
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='core')
    op.drop_index(op.f('ix_core_notifications_user_id'), table_name='notifications', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index(op.f('ix_core_settings_org_id'), table_name='settings', schema='core')
    op.drop_table('settings', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('branches', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_index(op.f('ix_core_permissions_module'), table_name='permissions', schema='core')
    op.drop_index(op.f('ix_core_permissions_code'), table_name='permissions', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('organizations', schema='core')
    op.drop_index(op.f('ix_core_document_sequences_org_id'), table_name='document_sequences', schema='core')
    op.drop_table('document_sequences', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_user_id'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_org_id'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_entity_type'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_created_at'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_action'), table_name='audit_logs', schema='core')
    op.drop_table('audit_logs', schema='core')
    # ### end Alembic commands ###
