"""quotations

Revision ID: bc18dd068050
Revises: 0458859fae6a
Create Date: 2026-09-26 18:08:46.996962
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bc18dd068050'
down_revision: str | None = '0458859fae6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.Date(), nullable=True),
    sa.Column('accepted_at', sa.Date(), nullable=True),
    sa.Column('converted_order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm.contacts.id'], name=op.f('fk_quotations_customer_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_quotations_org_id')),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_quotations_number'), 'quotations', ['number'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_quotations_org_id'), 'quotations', ['org_id'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_quotations_status'), 'quotations', ['status'], unique=False, schema='sales')
    op.create_table('quotation_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=True),
    sa.Column('tax_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_quotation_lines_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['sales.quotations.id'], name=op.f('fk_quotation_lines_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['catalog.taxes.id'], name=op.f('fk_quotation_lines_tax_id_taxes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_lines')),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_quotation_lines_quotation_id'), 'quotation_lines', ['quotation_id'], unique=False, schema='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_quotation_lines_quotation_id'), table_name='quotation_lines', schema='sales')
    op.drop_table('quotation_lines', schema='sales')
    op.drop_index(op.f('ix_sales_quotations_status'), table_name='quotations', schema='sales')
    op.drop_index(op.f('ix_sales_quotations_org_id'), table_name='quotations', schema='sales')
    op.drop_index(op.f('ix_sales_quotations_number'), table_name='quotations', schema='sales')
    op.drop_table('quotations', schema='sales')
    # ### end Alembic commands ###
