"""credit note fields

Revision ID: cfdb5277a3cb
Revises: bc18dd068050
Create Date: 2026-09-26 18:57:39.536344
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cfdb5277a3cb'
down_revision: str | None = 'bc18dd068050'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('original_invoice_id', sa.Uuid(), nullable=True), schema='invoicing')
    op.add_column('invoices', sa.Column('applied_credits', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False), schema='invoicing')
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=12),
               existing_nullable=False,
               schema='invoicing')
    op.create_index(op.f('ix_invoicing_invoices_original_invoice_id'), 'invoices', ['original_invoice_id'], unique=False, schema='invoicing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoicing_invoices_original_invoice_id'), table_name='invoices', schema='invoicing')
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False,
               schema='invoicing')
    op.drop_column('invoices', 'applied_credits', schema='invoicing')
    op.drop_column('invoices', 'original_invoice_id', schema='invoicing')
    # ### end Alembic commands ###
