"""user email prefs

Revision ID: e588436554b0
Revises: 3dd3b49c3f42
Create Date: 2026-09-26 20:35:06.489492
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e588436554b0'
down_revision: str | None = '3dd3b49c3f42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_prefs', schema='core')
    # ### end Alembic commands ###
