"""hr tables

Revision ID: f2a78aa74f70
Revises: b667c1134da5
Create Date: 2026-09-26 21:13:14.156667
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f2a78aa74f70'
down_revision: str | None = 'b667c1134da5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "hr"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_departments_org_id'), 'departments', ['org_id'], unique=False, schema='hr')
    op.create_table('employees',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('terminated_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr.departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_employees_org_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_employees_user_id')),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_employees_number'), 'employees', ['number'], unique=False, schema='hr')
    op.create_foreign_key(
        'fk_departments_manager_id_employees', 'departments', 'employees',
        ['manager_id'], ['id'], source_schema='hr', referent_schema='hr',
        ondelete='SET NULL',
    )
    op.create_index(op.f('ix_hr_employees_org_id'), 'employees', ['org_id'], unique=False, schema='hr')
    op.create_table('leave_types',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('days_per_year', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('accrues', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types')),
    sa.UniqueConstraint('org_id', 'name', name=op.f('uq_leave_types_org_id')),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_leave_types_org_id'), 'leave_types', ['org_id'], unique=False, schema='hr')
    op.create_table('leave_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['core.users.id'], name=op.f('fk_leave_requests_approver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employees.id'], name=op.f('fk_leave_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['hr.leave_types.id'], name=op.f('fk_leave_requests_type_id_leave_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests')),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_leave_requests_org_id'), 'leave_requests', ['org_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_leave_requests_status'), 'leave_requests', ['status'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_leave_requests_status'), table_name='leave_requests', schema='hr')
    op.drop_index(op.f('ix_hr_leave_requests_org_id'), table_name='leave_requests', schema='hr')
    op.drop_index(op.f('ix_hr_leave_requests_employee_id'), table_name='leave_requests', schema='hr')
    op.drop_table('leave_requests', schema='hr')
    op.drop_index(op.f('ix_hr_leave_types_org_id'), table_name='leave_types', schema='hr')
    op.drop_table('leave_types', schema='hr')
    op.drop_index(op.f('ix_hr_employees_org_id'), table_name='employees', schema='hr')
    op.drop_index(op.f('ix_hr_employees_number'), table_name='employees', schema='hr')
    op.drop_table('employees', schema='hr')
    op.drop_index(op.f('ix_hr_departments_org_id'), table_name='departments', schema='hr')
    op.drop_table('departments', schema='hr')
    # ### end Alembic commands ###
