"""sales and purchasing tables

Revision ID: fd4d2439f3d1
Revises: aa3464ba149d
Create Date: 2026-09-25 22:35:04.596516
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fd4d2439f3d1'
down_revision: str | None = 'aa3464ba149d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.Date(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_purchase_orders_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['crm.contacts.id'], name=op.f('fk_purchase_orders_supplier_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_purchase_orders_org_id')),
    schema='purchasing'
    )
    op.create_index(op.f('ix_purchasing_purchase_orders_number'), 'purchase_orders', ['number'], unique=False, schema='purchasing')
    op.create_index(op.f('ix_purchasing_purchase_orders_org_id'), 'purchase_orders', ['org_id'], unique=False, schema='purchasing')
    op.create_index(op.f('ix_purchasing_purchase_orders_status'), 'purchase_orders', ['status'], unique=False, schema='purchasing')
    op.create_table('sales_orders',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.Date(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['core.branches.id'], name=op.f('fk_sales_orders_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm.contacts.id'], name=op.f('fk_sales_orders_customer_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_orders')),
    sa.UniqueConstraint('org_id', 'number', name=op.f('uq_sales_orders_org_id')),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sales_orders_number'), 'sales_orders', ['number'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_sales_orders_org_id'), 'sales_orders', ['org_id'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_sales_orders_status'), 'sales_orders', ['status'], unique=False, schema='sales')
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=True),
    sa.Column('tax_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchasing.purchase_orders.id'], name=op.f('fk_purchase_order_lines_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_purchase_order_lines_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_id'], ['catalog.taxes.id'], name=op.f('fk_purchase_order_lines_tax_id_taxes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines')),
    schema='purchasing'
    )
    op.create_index(op.f('ix_purchasing_purchase_order_lines_order_id'), 'purchase_order_lines', ['order_id'], unique=False, schema='purchasing')
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom_code', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=True),
    sa.Column('tax_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales.sales_orders.id'], name=op.f('fk_sales_order_lines_order_id_sales_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_sales_order_lines_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_id'], ['catalog.taxes.id'], name=op.f('fk_sales_order_lines_tax_id_taxes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order_lines')),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sales_order_lines_order_id'), 'sales_order_lines', ['order_id'], unique=False, schema='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_sales_order_lines_order_id'), table_name='sales_order_lines', schema='sales')
    op.drop_table('sales_order_lines', schema='sales')
    op.drop_index(op.f('ix_purchasing_purchase_order_lines_order_id'), table_name='purchase_order_lines', schema='purchasing')
    op.drop_table('purchase_order_lines', schema='purchasing')
    op.drop_index(op.f('ix_sales_sales_orders_status'), table_name='sales_orders', schema='sales')
    op.drop_index(op.f('ix_sales_sales_orders_org_id'), table_name='sales_orders', schema='sales')
    op.drop_index(op.f('ix_sales_sales_orders_number'), table_name='sales_orders', schema='sales')
    op.drop_table('sales_orders', schema='sales')
    op.drop_index(op.f('ix_purchasing_purchase_orders_status'), table_name='purchase_orders', schema='purchasing')
    op.drop_index(op.f('ix_purchasing_purchase_orders_org_id'), table_name='purchase_orders', schema='purchasing')
    op.drop_index(op.f('ix_purchasing_purchase_orders_number'), table_name='purchase_orders', schema='purchasing')
    op.drop_table('purchase_orders', schema='purchasing')
    # ### end Alembic commands ###
