#!/usr/bin/env bash
# Pull-based deploy for a single-server demo host.
#
#   deploy/deploy.sh            redeploy only if origin/main moved (cron: every minute)
#   deploy/deploy.sh --force    redeploy now
#
# First run generates .env with random secrets (never committed; later runs
# never touch it). Everything runs in Docker; the only published port is the
# web container on 127.0.0.1:$PROXY_PORT, which cloudflared routes publicly.
set -euo pipefail

cd "$(dirname "$0")/.."
COMPOSE=(docker compose -f docker-compose.prod.yml)
BRANCH=main
PORT="${PROXY_PORT:-30001}"

log() { echo "$(date -u +%FT%TZ) $*"; }

# One deploy at a time (cron fires every minute; a build can take longer).
exec 9>.deploy.lock
flock -n 9 || exit 0

if [[ ! -f .env ]]; then
  log "generating .env"
  secret() { openssl rand -hex "$1"; }
  pg_password=$(secret 16)
  cat > .env <<EOF
# Generated by deploy/deploy.sh on $(date -u +%F) — server-local, never committed.
ENVIRONMENT=prod
PROXY_PORT=${PORT}

POSTGRES_USER=erp
POSTGRES_PASSWORD=${pg_password}
POSTGRES_DB=erp
DATABASE_URL=postgresql+asyncpg://erp:${pg_password}@postgres:5432/erp
REDIS_URL=redis://redis:6379/0

S3_ACCESS_KEY=erp
S3_SECRET_KEY=$(secret 16)
S3_BUCKET=erp

JWT_SECRET=$(secret 32)

ORG_NAME="Demo Company"
BASE_CURRENCY=USD
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=$(secret 8)

# Demo host: seed one user per role + demo data on every deploy (idempotent).
DEMO_SEED=true
ALLOW_TEST_USERS=true
TEST_USER_PASSWORD=$(secret 6)
EOF
  chmod 600 .env
  FORCE=1
fi

git fetch --quiet origin "$BRANCH"
if [[ "${1:-}" != "--force" && -z "${FORCE:-}" && "$(git rev-parse HEAD)" == "$(git rev-parse "origin/$BRANCH")" ]]; then
  exit 0  # nothing new
fi

log "deploying $(git rev-parse --short "origin/$BRANCH")"
git reset --quiet --hard "origin/$BRANCH"
"${COMPOSE[@]}" up -d --build --remove-orphans

# The api seeds org/roles/admin at start; demo hosts also get role users + data.
if grep -q '^DEMO_SEED=true' .env; then
  for _ in $(seq 1 60); do
    "${COMPOSE[@]}" exec -T api python -c \
      "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz')" \
      >/dev/null 2>&1 && break
    sleep 3
  done
  "${COMPOSE[@]}" exec -T api python -m app.core.seed_test_users
  "${COMPOSE[@]}" exec -T api python -m app.core.seed_demo
fi

docker image prune -f >/dev/null  # drop superseded build layers
log "deployed — http://127.0.0.1:$(grep '^PROXY_PORT=' .env | cut -d= -f2)"
