"""Permission catalog — the single source of truth, seeded into the database.

Codes follow `module.resource.action`.
"""

SYSTEM_ROLES: dict[str, dict] = {
    "admin": {
        "name": "Administrator",
        "description": "Full access to every module.",
        "permissions": "*",
    },
    "accountant": {
        "name": "Accountant",
        "description": "Invoicing, payments, accounting, and reports.",
        "permissions": [
            "core.user.read",
            "core.audit.read",
            "crm.contact.read",
            "catalog.product.read",
            "inventory.stock.read",
            "invoicing.invoice.read",
            "invoicing.invoice.create",
            "invoicing.invoice.update",
            "invoicing.invoice.post",
            "invoicing.invoice.void",
            "invoicing.payment.read",
            "invoicing.payment.create",
            "accounting.account.read",
            "accounting.entry.read",
            "accounting.entry.create",
            "reports.view",
        ],
    },
    "sales": {
        "name": "Sales",
        "description": "Customers and the sell cycle.",
        "permissions": [
            "crm.contact.read",
            "crm.contact.create",
            "crm.contact.update",
            "catalog.product.read",
            "sales.quote.read",
            "sales.quote.create",
            "sales.quote.update",
            "sales.quote.cancel",
            "sales.order.read",
            "sales.order.create",
            "sales.order.update",
            "sales.order.confirm",
            "sales.order.cancel",
            "invoicing.invoice.read",
            "invoicing.invoice.create",
            "reports.view",
        ],
    },
    "purchasing": {
        "name": "Purchasing",
        "description": "Suppliers and the buy cycle.",
        "permissions": [
            "crm.contact.read",
            "crm.contact.create",
            "crm.contact.update",
            "catalog.product.read",
            "catalog.product.create",
            "catalog.product.update",
            "purchasing.order.read",
            "purchasing.order.create",
            "purchasing.order.update",
            "purchasing.order.confirm",
            "purchasing.order.cancel",
            "inventory.receipt.read",
            "inventory.receipt.create",
            "inventory.receipt.post",
            "reports.view",
        ],
    },
    "warehouse": {
        "name": "Warehouse",
        "description": "Stock, receipts, deliveries, adjustments.",
        "permissions": [
            "catalog.product.read",
            "inventory.stock.read",
            "inventory.receipt.read",
            "inventory.receipt.create",
            "inventory.receipt.post",
            "inventory.delivery.read",
            "inventory.delivery.create",
            "inventory.delivery.post",
            "inventory.adjustment.read",
            "inventory.adjustment.create",
            "inventory.adjustment.post",
            "inventory.warehouse.read",
            "sales.order.read",
            "purchasing.order.read",
        ],
    },
    "viewer": {
        "name": "Viewer",
        "description": "Read-only access across modules.",
        "permissions": [
            "core.audit.read",
            "crm.contact.read",
            "catalog.product.read",
            "catalog.tax.read",
            "sales.order.read",
            "purchasing.order.read",
            "inventory.stock.read",
            "invoicing.invoice.read",
            "invoicing.payment.read",
            "accounting.account.read",
            "accounting.entry.read",
            "reports.view",
        ],
    },
}

# (code, module, action, description)
PERMISSION_CATALOG: list[tuple[str, str, str, str]] = [
    # core
    ("core.user.read", "core", "read", "List and view users"),
    ("core.user.create", "core", "create", "Create users"),
    ("core.user.update", "core", "update", "Update users, roles, activation"),
    ("core.role.read", "core", "read", "List roles and permissions"),
    ("core.role.create", "core", "create", "Create custom roles"),
    ("core.role.update", "core", "update", "Update custom roles"),
    ("core.org.read", "core", "read", "View organization profile"),
    ("core.org.update", "core", "update", "Edit organization profile"),
    ("core.branch.read", "core", "read", "View branches"),
    ("core.branch.create", "core", "create", "Create branches"),
    ("core.branch.update", "core", "update", "Edit branches"),
    ("core.settings.read", "core", "read", "Read settings"),
    ("core.settings.update", "core", "update", "Change settings"),
    ("core.audit.read", "core", "read", "View the audit log"),
    ("core.notification.read", "core", "read", "Read own notifications"),
    # crm
    ("crm.contact.read", "crm", "read", "View customers and suppliers"),
    ("crm.contact.create", "crm", "create", "Create contacts"),
    ("crm.contact.update", "crm", "update", "Edit contacts"),
    ("crm.contact.delete", "crm", "delete", "Delete unreferenced contacts"),
    ("crm.contact.archive", "crm", "archive", "Archive contacts"),
    # catalog
    ("catalog.product.read", "catalog", "read", "View products"),
    ("catalog.product.create", "catalog", "create", "Create products"),
    ("catalog.product.update", "catalog", "update", "Edit products"),
    ("catalog.product.delete", "catalog", "delete", "Delete unreferenced products"),
    ("catalog.product.archive", "catalog", "archive", "Archive products"),
    ("catalog.category.read", "catalog", "read", "View categories"),
    ("catalog.category.create", "catalog", "create", "Create categories"),
    ("catalog.category.update", "catalog", "update", "Edit categories"),
    ("catalog.category.delete", "catalog", "delete", "Delete categories"),
    ("catalog.tax.read", "catalog", "read", "View tax rates"),
    ("catalog.tax.create", "catalog", "create", "Create tax rates"),
    ("catalog.tax.update", "catalog", "update", "Edit tax rates"),
    ("catalog.uom.read", "catalog", "read", "View units of measure"),
    ("catalog.uom.create", "catalog", "create", "Create units of measure"),
    ("catalog.uom.update", "catalog", "update", "Edit units of measure"),
    # sales
    ("sales.quote.read", "sales", "read", "View quotations"),
    ("sales.quote.create", "sales", "create", "Create quotations"),
    ("sales.quote.update", "sales", "update", "Edit/send/accept quotations"),
    ("sales.quote.cancel", "sales", "cancel", "Cancel quotations"),
    ("sales.order.read", "sales", "read", "View sales orders"),
    ("sales.order.create", "sales", "create", "Create sales orders"),
    ("sales.order.update", "sales", "update", "Edit draft sales orders"),
    ("sales.order.confirm", "sales", "confirm", "Confirm sales orders"),
    ("sales.order.cancel", "sales", "cancel", "Cancel sales orders"),
    # purchasing
    ("purchasing.order.read", "purchasing", "read", "View purchase orders"),
    ("purchasing.order.create", "purchasing", "create", "Create purchase orders"),
    ("purchasing.order.update", "purchasing", "update", "Edit draft purchase orders"),
    ("purchasing.order.confirm", "purchasing", "confirm", "Confirm purchase orders"),
    ("purchasing.order.cancel", "purchasing", "cancel", "Cancel purchase orders"),
    # inventory
    ("inventory.stock.read", "inventory", "read", "View stock on hand and moves"),
    ("inventory.receipt.read", "inventory", "read", "View receipts"),
    ("inventory.receipt.create", "inventory", "create", "Create receipts"),
    ("inventory.receipt.post", "inventory", "post", "Post receipts (moves stock)"),
    ("inventory.receipt.void", "inventory", "void", "Void posted receipts"),
    ("inventory.delivery.read", "inventory", "read", "View deliveries"),
    ("inventory.delivery.create", "inventory", "create", "Create deliveries"),
    ("inventory.delivery.post", "inventory", "post", "Post deliveries (moves stock)"),
    ("inventory.delivery.void", "inventory", "void", "Void posted deliveries"),
    ("inventory.adjustment.read", "inventory", "read", "View adjustments"),
    ("inventory.adjustment.create", "inventory", "create", "Create stock adjustments"),
    ("inventory.adjustment.post", "inventory", "post", "Post stock adjustments"),
    ("inventory.warehouse.read", "inventory", "read", "View warehouses"),
    ("inventory.warehouse.create", "inventory", "create", "Create warehouses"),
    ("inventory.warehouse.update", "inventory", "update", "Edit warehouses"),
    # invoicing
    ("invoicing.invoice.read", "invoicing", "read", "View AR/AP invoices"),
    ("invoicing.invoice.create", "invoicing", "create", "Create invoices and bills"),
    ("invoicing.invoice.update", "invoicing", "update", "Edit draft invoices"),
    ("invoicing.invoice.post", "invoicing", "post", "Post invoices"),
    ("invoicing.invoice.void", "invoicing", "void", "Void posted invoices"),
    ("invoicing.payment.read", "invoicing", "read", "View payments"),
    ("invoicing.payment.create", "invoicing", "create", "Record payments"),
    ("invoicing.payment.void", "invoicing", "void", "Void payments"),
    # accounting
    ("accounting.account.read", "accounting", "read", "View chart of accounts"),
    ("accounting.account.create", "accounting", "create", "Create accounts"),
    ("accounting.account.update", "accounting", "update", "Edit non-system accounts"),
    ("accounting.entry.read", "accounting", "read", "View journal entries and ledger"),
    ("accounting.entry.create", "accounting", "create", "Create manual journal entries"),
    # reporting
    ("reports.view", "reporting", "read", "Run reports and view dashboards"),
]


def system_role_permissions(code: str) -> list[str]:
    mapping = SYSTEM_ROLES[code]["permissions"]
    if mapping == "*":
        return [row[0] for row in PERMISSION_CATALOG]
    return list(mapping)
